team1-monew/sb02-monew-team1

src/main/java/com/team1/monew/article/dto/ArticleDto.java, src/main/java/com/team1/monew/article/dto/ArticleRestoreResultDto.java, src/main/java/com/team1/monew/article/dto/ArticleViewDto.java, src/main/java/com/team1/monew/comment/dto/CommentActivityDto.java, src/main/java/com/team1/monew/comment/dto/CommentDto.java, src/main/java/com/team1/monew/comment/dto/CommentLikeActivityDto.java, src/main/java/com/team1/monew/comment/dto/CommentLikeDto.java, src/main/java/com/team1/monew/comment/dto/CommentRegisterRequest.java, src/main/java/com/team1/monew/comment/dto/CommentUpdateRequest.java, src/main/java/com/team1/monew/common/dto/CursorPageResponse.java, src/main/java/com/team1/monew/interest/dto/InterestDto.java, src/main/java/com/team1/monew/interest/dto/InterestRegisterRequest.java, src/main/java/com/team1/monew/interest/dto/InterestUpdateRequest.java, src/main/java/com/team1/monew/notification/dto/NotificationDto.java, src/main/java/com/team1/monew/subscription/dto/SubscriptionDto.java, src/main/java/com/team1/monew/user/dto/UserDto.java, src/main/java/com/team1/monew/user/dto/UserLoginRequest.java, src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java, src/main/java/com/team1/monew/user/dto/UserUpdateRequest.java, src/main/java/com/team1/monew/useractivity/dto/UserActivityDto.java
KAN-118
DTO 설계 및 구현
어떤 변경 사항이 있나요?
=> feat: KAN-118 DTO 설계 및 구현

src/main/java/com/team1/monew/exception/Code.java, src/main/java/com/team1/monew/exception/ErrorCode.java, src/main/java/com/team1/monew/exception/ErrorResponse.java, src/main/java/com/team1/monew/exception/GlobalExceptionHandler.java, src/main/java/com/team1/monew/exception/RestException.java, src/main/resources/application.properties, src/main/resources/application.yml
KAN-119
에러 및 예외 처리 설계 및 구현
어떤 변경 사항이 있나요?
=> feat: KAN-119 에러 및 예외 처리 설계 및 구현

src/main/java/com/team1/monew/article/controller/ArticleController.java, src/main/java/com/team1/monew/article/dto/ArticleDto.java, src/main/java/com/team1/monew/article/dto/ArticleViewDto.java, src/main/java/com/team1/monew/article/entity/Article.java, src/main/java/com/team1/monew/article/entity/ArticleView.java, src/main/java/com/team1/monew/article/mapper/ArticleMapper.java, src/main/java/com/team1/monew/article/mapper/ArticleViewMapper.java, src/main/java/com/team1/monew/article/repository/ArticleRepository.java, src/main/java/com/team1/monew/article/repository/ArticleViewRepository.java, src/main/java/com/team1/monew/article/service/ArticleService.java, src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
KAN-32
CRUD 계층별 설계 및 구현
어떤 변경 사항이 있나요?
=> feat: KAN-32 CRUD 계층별 설계 및 구현

src/main/java/com/team1/monew/comment/controller/CommentController.java, src/main/java/com/team1/monew/comment/dto/CommentUpdateRequest.java, src/main/java/com/team1/monew/comment/mapper/CommentMapper.java, src/main/java/com/team1/monew/comment/service/CommentService.java, src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java, src/main/java/com/team1/monew/comment/service/usecase/UpdateCommentUseCase.java, src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java, src/test/java/com/team1/monew/comment/service/CommentServiceImplTest.java, src/test/resources/application-test.yaml
KAN-168
댓글 등록 리팩토링 및 댓글 수정 API 구현
어떤 변경 사항이 있나요?
=> feat: KAN-168 댓글 수정

src/main/java/com/team1/monew/comment/controller/CommentController.java, src/main/java/com/team1/monew/comment/service/CommentService.java, src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java, src/main/java/com/team1/monew/comment/service/usecase/DeleteCommentUseCase.java, src/test/java/com/team1/monew/comment/service/CommentServiceImplTest.java
KAN-167
댓글 논리/물리 삭제 API 구현
어떤 변경 사항이 있나요?
=> feat: KAN-167 댓글 삭제

src/main/java/com/team1/monew/interest/controller/InterestController.java, src/main/java/com/team1/monew/interest/service/InterestServiceImpl.java, src/test/java/com/team1/monew/interest/service/InterestServiceTest.java
KAN-195
- 관심사 삭제 API 구현
- InterestServiceTest 관심사 삭제 단위 테스트 작성
어떤 변경 사항이 있나요?
=> feat: KAN-195 관심사 삭제

src/main/java/com/team1/monew/user/controller/UserController.java, src/main/java/com/team1/monew/user/dto/UserDto.java, src/main/java/com/team1/monew/user/dto/UserLoginRequest.java, src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java, src/main/java/com/team1/monew/user/entity/User.java, src/main/java/com/team1/monew/user/mapper/UserMapper.java, src/main/java/com/team1/monew/user/repository/UserRepository.java, src/main/java/com/team1/monew/user/service/UserService.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/MonewApplicationTests.java, src/test/java/com/team1/monew/user/UserApiIntegrationTest.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
KAN-16
사용자 등록 및 로그인
어떤 변경 사항이 있나요?
=> feat: KAN-16 사용자 등록 및 로그인

src/main/java/com/team1/monew/user/controller/UserController.java, src/main/java/com/team1/monew/user/dto/UserUpdateRequest.java, src/main/java/com/team1/monew/user/entity/User.java, src/main/java/com/team1/monew/user/service/UserService.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/user/UserApiIntegrationTest.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
KAN-17
사용자 정보 수정 / 삭제
어떤 변경 사항이 있나요?
=> feat: KAN-17 사용자 정보 수정 / 삭제

src/main/java/com/team1/monew/comment/controller/CommentController.java, src/main/java/com/team1/monew/comment/dto/CommentLikeDto.java, src/main/java/com/team1/monew/comment/entity/CommentLike.java, src/main/java/com/team1/monew/comment/mapper/CommentLikeMapper.java, src/main/java/com/team1/monew/comment/repository/CommentLikeRepository.java, src/main/java/com/team1/monew/comment/service/CommentLikeService.java, src/main/java/com/team1/monew/comment/service/CommentLikeServiceImpl.java, src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java
KAN-52
댓글 좋아요, 좋아요 취소 API 추가
어떤 변경 사항이 있나요?
=> feat: KAN-52 댓글 좋아요 기능 추가

build.gradle, src/main/java/com/team1/monew/common/dto/CursorPageResponse.java, src/main/java/com/team1/monew/config/QueryDslConfig.java, src/main/java/com/team1/monew/interest/controller/InterestController.java, src/main/java/com/team1/monew/interest/dto/InterestDto.java, src/main/java/com/team1/monew/interest/dto/InterestSearchCondition.java, src/main/java/com/team1/monew/interest/mapper/InterestMapper.java, src/main/java/com/team1/monew/interest/mapper/PageResponseMapper.java, src/main/java/com/team1/monew/interest/repository/InterestRepository.java, src/main/java/com/team1/monew/interest/repository/InterestRepositoryCustom.java, src/main/java/com/team1/monew/interest/repository/InterestRepositoryCustomImpl.java, src/main/java/com/team1/monew/interest/service/InterestService.java, src/main/java/com/team1/monew/interest/service/InterestServiceImpl.java, src/test/java/com/team1/monew/interest/config/TestQueryDslConfig.java, src/test/java/com/team1/monew/interest/repository/InterestRepositoryCustomImplTest.java, src/test/java/com/team1/monew/interest/repository/InterestRepositoryTest.java, src/test/java/com/team1/monew/interest/service/InterestServiceTest.java
KAN-76
- Querydsl 초기 세팅
- 관심사 조회 및 검색 API 구현 (정렬 + 커서 페이지네이션)
- Repository, Service 단위테스트 작성
어떤 변경 사항이 있나요?
=> feat: KAN-76 관심사 조회 및 검색 (정렬 + 커서 페이지네이션)

src/main/java/com/team1/monew/comment/repository/CommentRepository.java
KAN-225
뉴스기사 도메인에서 필요한 기사별 삭제되지 않은 댓글 개수 메서드 추가
어떤 변경 사항이 있나요?
=> feat: KAN-225 뉴스기사 도메인에서 필요한 기사별 삭제되지 않은 댓글 개수 메서드 추가

build.gradle, src/main/java/com/team1/monew/exception/ErrorCode.java, src/main/java/com/team1/monew/exception/ErrorResponse.java, src/main/java/com/team1/monew/exception/GlobalExceptionHandler.java, src/main/java/com/team1/monew/security/CustomUserDetails.java, src/main/java/com/team1/monew/security/HeaderUserAuthenticationFilter.java, src/main/java/com/team1/monew/security/SecurityConfig.java, src/main/java/com/team1/monew/security/SecurityPathUtil.java, src/main/java/com/team1/monew/user/controller/UserController.java, src/main/java/com/team1/monew/user/dto/UserLoginRequest.java, src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java, src/main/java/com/team1/monew/user/dto/UserUpdateRequest.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/security/HeaderUserAuthenticationFilterTest.java, src/test/java/com/team1/monew/security/SecurityConfigIntegrationTest.java, src/test/java/com/team1/monew/user/UserApiIntegrationTest.java
KAN-18 
인증 권한 및 유효성 검사
어떤 변경 사항이 있나요?
=> feat: KAN-18 인증 권한 및 유효성 검사

src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/test/java/com/team1/monew/article/service/ArticleServiceImplTest.java
KAN-42
단위 테스트 코드 작성
어떤 변경 사항이 있나요?
=> feat: KAN-42 테스트 코드 작성

src/main/java/com/team1/monew/article/collector/ChosunNewsCollector.java, src/main/java/com/team1/monew/article/collector/NaverNewsCollector.java, src/main/java/com/team1/monew/article/collector/NewsCollector.java, src/main/java/com/team1/monew/article/controller/ArticleController.java, src/main/java/com/team1/monew/article/dto/ArticleDto.java, src/main/java/com/team1/monew/article/dto/ArticleRestoreResultDto.java, src/main/java/com/team1/monew/article/dto/ArticleViewDto.java, src/main/java/com/team1/monew/article/dto/CollectedArticleDto.java, src/main/java/com/team1/monew/article/entity/Article.java, src/main/java/com/team1/monew/article/entity/ArticleInterest.java, src/main/java/com/team1/monew/article/entity/ArticleView.java, src/main/java/com/team1/monew/article/mapper/ArticleMapper.java, src/main/java/com/team1/monew/article/mapper/ArticleViewMapper.java, src/main/java/com/team1/monew/article/mapper/CollectedArticleMapper.java, src/main/java/com/team1/monew/article/repository/ArticleInterestRepository.java, src/main/java/com/team1/monew/article/repository/ArticleRepository.java, src/main/java/com/team1/monew/article/repository/ArticleRepositoryCustom.java, src/main/java/com/team1/monew/article/repository/ArticleRepositoryCustomImpl.java, src/main/java/com/team1/monew/article/repository/ArticleViewRepository.java, src/main/java/com/team1/monew/article/scheduler/NewsCollectorScheduler.java, src/main/java/com/team1/monew/article/service/ArticleService.java, src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/test/java/com/team1/monew/article/service/ArticleServiceImplTest.java
KAN-13 
뉴스 기사 관리
어떤 변경 사항이 있나요?
=> feat: KAN-13 뉴스 기사 관리

src/main/java/com/team1/monew/security/auth/CustomUserDetails.java, src/main/java/com/team1/monew/security/config/SecurityConfig.java, src/main/java/com/team1/monew/security/filter/ExceptionHandlingFilter.java, src/main/java/com/team1/monew/security/filter/HeaderUserAuthenticationFilter.java, src/main/java/com/team1/monew/security/handler/CustomAccessDeniedHandler.java, src/main/java/com/team1/monew/security/handler/CustomAuthenticationEntryPoint.java, src/main/java/com/team1/monew/security/support/ErrorResponseWriter.java, src/main/java/com/team1/monew/security/util/SecurityPathUtil.java, src/main/java/com/team1/monew/user/controller/UserController.java, src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java, src/main/java/com/team1/monew/user/entity/User.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/security/HeaderUserAuthenticationFilterTest.java
KAN-231
사용자 관리 수정
어떤 변경 사항이 있나요?
=> fix: KAN-231 사용자 관리 수정

src/main/java/com/team1/monew/interest/controller/InterestController.java, src/main/java/com/team1/monew/interest/entity/Interest.java, src/main/java/com/team1/monew/interest/mapper/InterestMapper.java, src/main/java/com/team1/monew/interest/repository/InterestRepository.java, src/main/java/com/team1/monew/interest/service/InterestService.java, src/main/java/com/team1/monew/interest/service/InterestServiceImpl.java, src/main/java/com/team1/monew/subscription/repository/SubscriptionRepository.java, src/main/java/com/team1/monew/subscription/service/SubscriptionServiceImpl.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/interest/service/InterestServiceTest.java, src/test/java/com/team1/monew/subscription/repository/SubscriptionRepositoryTest.java, src/test/java/com/team1/monew/subscription/service/SubscriptionServiceTest.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
KAN-232
- interestDto에 구독여부 반영
- 구독자수 증가/감소 동시성 문제 해결
- 유저 삭제 시, 구독자 수 감소 기능 추가
- 테스트코드 수정
어떤 변경 사항이 있나요?
=> fix: KAN-232 관심사 관리 수정

src/main/java/com/team1/monew/article/repository/ArticleViewRepository.java, src/main/java/com/team1/monew/comment/dto/CommentActivityDto.java, src/main/java/com/team1/monew/comment/dto/CommentLikeActivityDto.java, src/main/java/com/team1/monew/comment/mapper/CommentLikeMapper.java, src/main/java/com/team1/monew/comment/mapper/CommentMapper.java, src/main/java/com/team1/monew/comment/repository/CommentLikeRepository.java, src/main/java/com/team1/monew/comment/repository/CommentRepository.java, src/main/java/com/team1/monew/useractivity/controller/UserActivityController.java, src/main/java/com/team1/monew/useractivity/dto/UserActivityDto.java, src/main/java/com/team1/monew/useractivity/dto/UserActivityParam.java, src/main/java/com/team1/monew/useractivity/entity/UserActivity.java, src/main/java/com/team1/monew/useractivity/mapper/UserActivityMapper.java, src/main/java/com/team1/monew/useractivity/service/UserActivityService.java, src/main/java/com/team1/monew/useractivity/service/UserActivityServiceImpl.java
KAN-281 
- 필요한 레포지토리 생성
- 유저 활동 내역 서비스 구현
- 유저 활동 내역 컨트롤러 구현
어떤 변경 사항이 있나요?
=> feat: KAN-281 활동 내역 조회 기본 요구사항 구현

build.gradle, src/main/java/com/team1/monew/MonewApplication.java, src/main/java/com/team1/monew/comment/event/CommentLikedEvent.java, src/main/java/com/team1/monew/comment/service/CommentLikeServiceImpl.java, src/main/java/com/team1/monew/notification/dto/ResourceType.java, src/main/java/com/team1/monew/notification/entity/Notification.java, src/main/java/com/team1/monew/notification/event/NotificationEventListener.java, src/main/java/com/team1/monew/notification/repository/NotificationRepository.java, src/main/java/com/team1/monew/notification/service/NotificationService.java, src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java, src/test/java/com/team1/monew/notification/event/CommentLikedEventAsyncTest.java, src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
KAN-67 
댓글 좋아요 알림 트리거
어떤 변경 사항이 있나요?
=> feat: KAN-67 댓글 좋아요 알림 트리거

build.gradle, src/main/java/com/team1/monew/common/S3Util.java, src/main/java/com/team1/monew/config/S3Config.java
KAN-264
AWS S3 관련 기능 구현
어떤 변경 사항이 있나요?
=> feat: KAN-264 AWS S3 관련 기능 구현

src/main/java/com/team1/monew/article/event/NewArticlesCollectedEvent.java, src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/notification/event/NotificationEventListener.java, src/main/java/com/team1/monew/notification/service/NotificationService.java, src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java, src/main/java/com/team1/monew/subscription/repository/SubscriptionRepository.java, src/test/java/com/team1/monew/notification/event/NewArticlesCollectedEventAsyncTest.java, src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
KAN-68
관심사 관련 기사 등록 시 알림 생성 트리거
어떤 변경 사항이 있나요?
=> feat: KAN-68 관심사 관련 기사 등록 시 알림 생성 트리거

src/main/java/com/team1/monew/article/controller/ArticleController.java, src/main/java/com/team1/monew/article/entity/Article.java, src/main/java/com/team1/monew/article/mapper/ArticleMapper.java, src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/common/S3Util.java
KAN-273
뉴스 기사 복구 기능 구현
어떤 변경 사항이 있나요?
=> feat: KAN-273 뉴스 기사 복구 기능 구현

src/test/java/com/team1/monew/article/config/ArticleBackupJobConfigTest.java, src/test/java/com/team1/monew/article/service/ArticleServiceImplTest.java
KAN-304
테스트 코드 작성
어떤 변경 사항이 있나요?
=> test: KAN-304 테스트 코드 작성

src/main/java/com/team1/monew/notification/controller/NotificationController.java, src/main/java/com/team1/monew/notification/repository/NotificationRepository.java, src/main/java/com/team1/monew/notification/service/NotificationService.java, src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java, src/test/java/com/team1/monew/notification/repository/NotificationRepositoryTest.java, src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
=> feat: KAN-258 알림 확인

build.gradle, src/main/java/com/team1/monew/article/event/NewArticlesCollectedEvent.java, src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/comment/event/CommentLikedEvent.java, src/main/java/com/team1/monew/comment/service/CommentLikeServiceImpl.java, src/main/java/com/team1/monew/notification/config/NotificationCleanupJobConfig.java, src/main/java/com/team1/monew/notification/controller/NotificationController.java, src/main/java/com/team1/monew/notification/dto/NotificationCursorRequest.java, src/main/java/com/team1/monew/notification/dto/NotificationDto.java, src/main/java/com/team1/monew/notification/dto/ResourceType.java, src/main/java/com/team1/monew/notification/entity/Notification.java, src/main/java/com/team1/monew/notification/event/NotificationEventListener.java, src/main/java/com/team1/monew/notification/mapper/NotificationPageResponseMapper.java, src/main/java/com/team1/monew/notification/repository/NotificationRepository.java, src/main/java/com/team1/monew/notification/repository/NotificationRepositoryCustom.java, src/main/java/com/team1/monew/notification/repository/NotificationRepositoryImpl.java, src/main/java/com/team1/monew/notification/scheduler/NotificationJobScheduler.java, src/main/java/com/team1/monew/notification/service/NotificationService.java, src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java, src/main/java/com/team1/monew/subscription/repository/SubscriptionRepository.java, src/test/java/com/team1/monew/notification/event/CommentLikedEventAsyncTest.java, src/test/java/com/team1/monew/notification/event/NewArticlesCollectedEventAsyncTest.java, src/test/java/com/team1/monew/notification/repository/NotificationRepositoryImplTest.java, src/test/java/com/team1/monew/notification/repository/NotificationRepositoryTest.java, src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
=> feat: KAN-64 알림 관리

src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/notification/config/NotificationCleanupJobConfig.java, src/main/java/com/team1/monew/notification/mapper/NotificationPageResponseMapper.java
KAN-329
알림 관리 수정
어떤 변경 사항이 있나요?
=> fix: KAN-329 알림 관리 수정

src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
KAN-345
- 활동 내역 관리 수정 (누락된 코드 추가)
어떤 변경 사항이 있나요?
=> modify: KAN-345-활동내역-관리-수정

src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/notification/mapper/NotificationPageResponseMapper.java, src/main/java/com/team1/monew/notification/repository/NotificationRepository.java, src/main/java/com/team1/monew/notification/repository/NotificationRepositoryImpl.java, src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java
KAN-344
3차 스프린트 fix
어떤 변경 사항이 있나요?
=> fix: KAN-344 3차 스프린트 fix

src/test/java/com/team1/monew/user/UserApiIntegrationTest.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
KAN-334
사용자 관리 테스트 코드
어떤 변경 사항이 있나요?
=> test: KAN-334 사용자 관리 테스트 코드

src/test/java/com/team1/monew/article/ArticleIntegrationTest.java, src/test/java/com/team1/monew/article/service/ArticleServiceImplTest.java
KAN-327
뉴스 기사 관리 테스트 코드
어떤 변경 사항이 있나요?
=> test: KAN-327 뉴스 기사 관리 테스트 코드

src/test/java/com/team1/monew/notification/NotificationIntegrationTest.java, src/test/java/com/team1/monew/notification/repository/NotificationRepositoryTest.java, src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
KAN-364
알림 관리 테스트 코드
어떤 변경 사항이 있나요?
=> test: KAN-364 알림 관리 테스트 코드

build.gradle, src/test/java/com/team1/monew/comment/CommentIntegrationTest.java, src/test/java/com/team1/monew/comment/CommentLikeIntegrationTest.java, src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java, src/test/java/com/team1/monew/comment/repository/CommentRepositoryImplTest.java, src/test/java/com/team1/monew/comment/service/CommentLikeServiceImplTest.java, src/test/java/com/team1/monew/comment/service/CommentServiceImplTest.java
KAN-336
댓글 관리 테스트 코드
어떤 변경 사항이 있나요?
=> test: KAN-336 댓글 관리 테스트 코드

build.gradle, src/test/java/com/team1/monew/useractivity/integration/UserActivityIntegrationTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/ArticleViewActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/CommentActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/CommentLikeActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/SubscriptionActivityBatchServiceTest.java
KAN-328
활동 내역 관리 테스트 코드
어떤 변경 사항이 있나요?
=> test: KAN-328 활동 내역 관리 테스트 코드

src/main/java/com/team1/monew/comment/event/CommentActivityEditedEvent.java, src/main/java/com/team1/monew/comment/event/listener/CommentActivityEventListener.java, src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java, src/test/java/com/team1/monew/comment/CommentIntegrationTest.java
KAN-380
댓글 수정 시 이벤트 기반 활동 내역 수정 구현
어떤 변경 사항이 있나요?
=> feat: KAN-380 댓글 수정 시 이벤트 기반 활동 내역 수정 구현

src/main/java/com/team1/monew/interest/entity/Interest.java, src/main/java/com/team1/monew/interest/repository/InterestRepositoryCustomImpl.java
KAN-387
- 관심사-키워드 N+1 문제 해결 (@BatchSize)
어떤 변경 사항이 있나요?
=> refactor: KAN-387 관심사 관리 코드 리팩토링

build.gradle, src/main/java/com/team1/monew/config/RetryConfig.java, src/main/java/com/team1/monew/exception/ErrorCode.java, src/main/java/com/team1/monew/user/event/UserCreateEvent.java, src/main/java/com/team1/monew/user/event/UserDeleteEvent.java, src/main/java/com/team1/monew/user/event/listener/UserEventListener.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
KAN-372
- 사용자 생성 시 이벤트 기반으로 MongoDB document 생성
- 사용자 삭제 시 이벤트 기반으로 MongoDB document 생성
- 재시도 로직 추가
어떤 변경 사항이 있나요?
=> refactor: KAN-372 사용자 이벤트 기반 리팩토링

build.gradle, src/main/java/com/team1/monew/article/event/listener/ArticleViewEventListener.java, src/main/java/com/team1/monew/comment/event/CommentActivityEditedEvent.java, src/main/java/com/team1/monew/comment/event/listener/CommentActivityEventListener.java, src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java, src/main/java/com/team1/monew/config/RetryConfig.java, src/main/java/com/team1/monew/exception/ErrorCode.java, src/main/java/com/team1/monew/interest/entity/Interest.java, src/main/java/com/team1/monew/interest/repository/InterestRepositoryCustomImpl.java, src/main/java/com/team1/monew/subscription/event/listener/SubscriptionEventListener.java, src/main/java/com/team1/monew/user/event/UserCreateEvent.java, src/main/java/com/team1/monew/user/event/UserDeleteEvent.java, src/main/java/com/team1/monew/user/event/listener/UserEventListener.java, src/main/java/com/team1/monew/user/service/UserServiceImpl.java, src/main/java/com/team1/monew/useractivity/scheduler/service/ArticleViewActivityBatchService.java, src/main/java/com/team1/monew/useractivity/scheduler/service/CommentActivityBatchService.java, src/main/java/com/team1/monew/useractivity/scheduler/service/CommentLikeActivityBatchService.java, src/main/java/com/team1/monew/useractivity/scheduler/service/SubscriptionActivityBatchService.java, src/test/java/com/team1/monew/article/integration/ArticleViewIntegrationTest.java, src/test/java/com/team1/monew/comment/CommentIntegrationTest.java, src/test/java/com/team1/monew/subscription/integration/SubscriptionIntegrationTest.java, src/test/java/com/team1/monew/user/UserApiIntegrationTest.java, src/test/java/com/team1/monew/user/service/UserServiceImplTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/ArticleViewActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/CommentActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/CommentLikeActivityBatchServiceTest.java, src/test/java/com/team1/monew/useractivity/scheduler/service/SubscriptionActivityBatchServiceTest.java
KAN-371
- KAN-380 댓글 수정 시 이벤트 기반 활동 내역 수정\
- KAN-387 관심사 관리 코드 리팩토링
- KAN-372 사용자 이벤트 기반 리팩토링
- KAN-373 활동 내역 스케쥴링 재시도 로직 추가
- KAN-376 이벤트 처리 재시도 로직 추가
어떤 변경 사항이 있나요?
=> refactor: KAN-371 코드 리팩토링

src/main/java/com/team1/monew/article/entity/ArticleView.java
KAN-399
articleView 엔티티 수정
어떤 변경 사항이 있나요?
=> modify: KAN-399 articleView 엔티티 수정

src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java, src/main/java/com/team1/monew/notification/controller/NotificationController.java
KAN-398
기사 수집 시 알림 버그 수정
어떤 변경 사항이 있나요?
=> fix: KAN-398 기사 수집 시 알림 버그 수정

src/main/java/com/team1/monew/article/repository/ArticleRepositoryCustomImpl.java
KAN-405
기사 논리 삭제 시 조회 관련 수정
어떤 변경 사항이 있나요?
=> fix: KAN-405 기사 논리 삭제 시 조회 관련 수정
